[features]
seeds = false
[programs.localnet]
tmp = "BgJ7a9UKRN5VUKXAgM6q3YiEugGvwqU8eoG1U3Qumvse"
[programs.devnet]
tmp = "BgJ7a9UKRN5VUKXAgM6q3YiEugGvwqU8eoG1U3Qumvse"
[programs.mainnet]
tmp = "BgJ7a9UKRN5VUKXAgM6q3YiEugGvwqU8eoG1U3Qumvse"
# orig - CRQXfRGq3wTkjt7JkqhojPLiKLYLjHPGLebnfiiQB46T
# new - BgJ7a9UKRN5VUKXAgM6q3YiEugGvwqU8eoG1U3Qumvse

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
# wallet = "../mainnet-fork/localnet_owner.key"
wallet = "~/.config/solana/uwuU3qc2RwN6CpzfBAhg6wAxiEx138jy5wB3Xvx18Rw.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

